#theme: jekyll-theme-slate
remote_theme: pmarsceill/just-the-docs
title: easy_cell_counter docs

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "https://github.com/DSPsleeporg/easy_cell_counter"